version: "3.8"

services:
  mealbot-discord:
    build:
      context: ./discord-bot
      dockerfile: Dockerfile
    container_name: mealbot-discord-bot
    restart: unless-stopped
    volumes:
      - ./service-account-keys.json:/app/credentials.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    env_file:
      - ./discord-bot/.env
    networks:
      - mealbot-network
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: mealbot-api
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ./api/data:/app/data # Mount a local 'data' directory to the container's /app/data
    environment:
      - NODE_ENV=production
    networks:
      - mealbot-network

networks:
  mealbot-network:
    driver: bridge
