[project]
name = "experience-api"
version = "0.1.0"
description = "FastAPI server for processing URLs"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"