name: 🏗️ Terraform CI

on:
  workflow_call:
    inputs:
      image_uri:
        description: "URI of the Docker image to deploy"
        required: true
        type: string
      project_id:
        description: "GCP Project ID"
        required: true
        type: string
      cloud_run_sa_email:
        description: "Service Account Email for Cloud Run"
        required: true
        type: string
      tf_bucket:
        description: "GCS Bucket for Terraform state"
        required: true
        type: string
      tf_api_token:
        description: "Terraform Cloud API Token"
        required: true
        type: string
      github_ref:
        description: "GitHub ref (e.g., refs/heads/main)"
        required: true
        type: string
      github_event_name:
        description: "GitHub event name (e.g., push)"
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ inputs.tf_api_token }}

      - name: Terraform Init
        run: cd terraform && terraform init -backend-config bucket=${{ inputs.tf_bucket }}

      - name: Terraform Format
        run: cd terraform && terraform fmt -check

      - name: Terraform Plan
        run: |
          cd terraform && terraform plan \
            -var cloud_run_image_uri="${{ inputs.image_uri }}" \
            -var project_id=${{ inputs.project_id }} \
            -var cloud_run_service_account=${{ inputs.cloud_run_sa_email }} \
            -var tf_state_bucket=${{ inputs.tf_bucket }} \
            -out "prod.tfplan"

      - name: Terraform Apply
        if: ${{ inputs.github_ref == 'refs/heads/main' && inputs.github_event_name == 'push' }}
        run: cd terraform && terraform apply "prod.tfplan"
