name: Terraform CI/CD
on:
  workflow_call:
    inputs:
      api_image_uri:
        required: true
        type: string
      discord_bot_image_uri:
        required: true
        type: string
      github_ref:
        required: true
        type: string
      github_event_name:
        required: true
        type: string

concurrency:
  group: terraform-global-lock
  cancel-in-progress: true # Cancel concurrent plan & apply

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Cloud Auth
        id: "auth"
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.ACTIONS_SA_EMAIL }}
          token_format: "access_token"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.tf_api_token }}

      - name: Terraform Init
        run: cd terraform && terraform init -backend-config bucket=${{ vars.TF_BUCKET }}

      - name: Terraform Format
        run: cd terraform && terraform fmt -check

      - name: Terraform Plan
        run: |
          cd terraform && terraform plan \
            -var cloud_run_discord_image_uri="${{ inputs.discord_bot_image_uri }}" \
            -var cloud_run_api_image_uri="${{ inputs.api_image_uri }}" \
            -var project_id=${{ vars.PROJECT_ID }} \
            -var tf_state_bucket=${{ vars.TF_BUCKET }} \
            -out "prod.tfplan"

      - name: Terraform Apply
        if: inputs.github_ref == 'refs/heads/main' && inputs.github_event_name == 'push'
        run: cd terraform && terraform apply "prod.tfplan"
